/*
 * FixForm.java
 *
 * Created on 27. srpen 2008, 10:14
 */

package ucitel.forms;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Iterator;
import org.jdesktop.application.Action;
import javax.swing.JOptionPane;
import ucitel.ConnectionToDB;
import ucitel.DirectionOfTranslation;
import ucitel.Example;
import ucitel.GuiDirection;
import ucitel.Teacher;
import ucitel.Ucitel;
/**
 *
 * @author  strafeldap
 */
public class FixForm extends javax.swing.JDialog {
   final public static int CURRENT = 1;
   final public static int PREVIOUS = 0;
   final private String vyber = "--vyber skupinu--";
   int id;

   private int cur_pre;
    //private boolean adding=false;
    /** Creates new form FixForm */
    public FixForm(java.awt.Frame parent) {
        super(parent);
        initComponents();
        JFrame mainFrame =Ucitel.getApplication().getMainFrame();
        this.setLocationRelativeTo(mainFrame);
        this.setModal(true);    

    }
    
    public FixForm(){
        initComponents();
        this.loadThemes();
        JFrame mainFrame =Ucitel.getApplication().getMainFrame();
        this.setLocationRelativeTo(mainFrame);
        this.setModal(true);    
    }
    
    public FixForm(Teacher uc, int current){
        initComponents();
        this.cur_pre = current;
        Example example;
        if (current==1){
            example = uc.getCurrentExample();
        } else {
            example = uc.getPreviousExample();
        }

        JFrame mainFrame =Ucitel.getApplication().getMainFrame();
        this.setLocationRelativeTo(mainFrame);
        this.setModal(true);
        this.loadThemes();
        
        ucitel = uc;
        deleteB.setText("Smazat");
        foreignL.setText(GuiDirection.getInstance().getForeignLanguage().toString());
        foreignField.setText(example.getForeign());
        czechField.setText(example.getCzech());
        hintTF.setText(example.getHint());
        id = example.getID();

        grammarCB.setSelected(example.isGrammar());

        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        czechField = new javax.swing.JTextField();
        foreignField = new javax.swing.JTextField();
        foreignL = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hintTF = new javax.swing.JTextArea();
        deleteB = new javax.swing.JButton();
        grammarCB = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        themeCB = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ucitel.Ucitel.class).getContext().getResourceMap(FixForm.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        czechField.setText(resourceMap.getString("czechField.text")); // NOI18N
        czechField.setName("czechField"); // NOI18N
        czechField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                czechFieldKeyReleased(evt);
            }
        });

        foreignField.setText(resourceMap.getString("foreignField.text")); // NOI18N
        foreignField.setName("foreignField"); // NOI18N

        foreignL.setText(resourceMap.getString("foreignL.text")); // NOI18N
        foreignL.setName("foreignL"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ucitel.Ucitel.class).getContext().getActionMap(FixForm.class, this);
        jButton3.setAction(actionMap.get("swap")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        hintTF.setColumns(20);
        hintTF.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        hintTF.setLineWrap(true);
        hintTF.setRows(5);
        hintTF.setWrapStyleWord(true);
        hintTF.setName("hintTF"); // NOI18N
        jScrollPane1.setViewportView(hintTF);

        deleteB.setText(resourceMap.getString("deleteB.text")); // NOI18N
        deleteB.setName("deleteB"); // NOI18N
        deleteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBActionPerformed(evt);
            }
        });

        grammarCB.setText(resourceMap.getString("grammarCB.text")); // NOI18N
        grammarCB.setName("grammarCB"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        themeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        themeCB.setName("themeCB"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(foreignL)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(grammarCB))
                        .addComponent(czechField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(foreignField, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(themeCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(foreignL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foreignField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(grammarCB))
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(czechField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    fix();
}//GEN-LAST:event_jButton1ActionPerformed
private void fix(){
    String newCzech = czechField.getText();
    String newEnglish = foreignField.getText();
    String newHint = hintTF.getText();
    String theme = (String) themeCB.getSelectedItem();

    int grammar;

    if (grammarCB.isSelected()){
        grammar = 1;
    } else {
        grammar = 0;
    }

      if (cur_pre == this.CURRENT){
        

        if ( ucitel.fix_current(newCzech,newEnglish,newHint, grammar, theme) ){
            this.dispose();
            ucitel.getQuestionFromDB();
        } else {
            JOptionPane.showMessageDialog(GUI.getInstance().getComponent(), "Chyba", "Chyba: Slovíčko nebylo opraveno",JOptionPane.OK_OPTION);
        }
    } else {
        if ( ucitel.fix_previous(newCzech,newEnglish,newHint, grammar, theme) ){
            this.dispose();
            ucitel.getQuestionFromDB();
        } else {
            JOptionPane.showMessageDialog(GUI.getInstance().getComponent(), "Chyba", "Chyba: Slovíčko nebylo opraveno",JOptionPane.OK_OPTION);
        }
    }

    
    
    
}
private void czechFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_czechFieldKeyReleased
    if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        fix();
    }
}//GEN-LAST:event_czechFieldKeyReleased

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

private void loadThemes() {

        try {
            themeCB.removeAllItems();

            ArrayList<String> themes = ConnectionToDB.getInstance().getThemes();
            Iterator i = themes.iterator();
            while (true == i.hasNext()) {
                themeCB.addItem(i.next());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(GUI.getInstance().getComponent(), e.toString(), "Error" ,JOptionPane.OK_OPTION);
            e.toString();
            e.printStackTrace();
        }

        String theme = GUI.getInstance().getTheme();
        if (theme == null){
            
            themeCB.addItem(vyber);
            themeCB.setSelectedItem(vyber);
        }
        else {
            themeCB.setSelectedItem(theme);
        }



    }

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

private void deleteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBActionPerformed
        //try {
            try {
                ConnectionToDB.getInstance().deleteCurrent(id);
            } catch (Exception ex) {
                Logger.getLogger(FixForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        /*} catch (SQLException ex) {
            Logger.getLogger(FixForm.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
            ex.toString();
            System.exit(0);
        }*/
        this.dispose();
}//GEN-LAST:event_deleteBActionPerformed

    @Action
    public void swap() {
    String first=czechField.getText();
    czechField.setText(foreignField.getText());
    foreignField.setText(first);
    }

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FixForm().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField czechField;
    private javax.swing.JButton deleteB;
    private javax.swing.JTextField foreignField;
    private javax.swing.JLabel foreignL;
    private javax.swing.JCheckBox grammarCB;
    private javax.swing.JTextArea hintTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox themeCB;
    // End of variables declaration//GEN-END:variables
    private Teacher ucitel;
    //private boolean englishChanged;
    //private boolean czechChanged;
    DirectionOfTranslation direction;
}
