/*
 * StatsForm.java
 *
 * Created on 28. srpen 2008, 12:54
 */
package ucitel.forms;

import javax.swing.JOptionPane;
import ucitel.ConnectionToDB;
import ucitel.Example;
import ucitel.GuiDirection;

/**
 *
 * @author  strafeldap
 */
public class StatsForm extends javax.swing.JDialog {

	/** Creates new form StatsForm */
	public StatsForm(java.awt.Frame parent) {
		super(parent);
		initComponents();
		direction = GuiDirection.getInstance();
		this.setModal(true);
		this.setTitle("Statistika");
		reset.setText("Reset");
		redraw();

	}
	GuiDirection direction;

	private void redraw() {
		try {
			conn = ConnectionToDB.getInstance();
			int wordCnt = conn.getNumberOfWords(direction);
			numberOfWordsLabel.setText(Integer.toString(wordCnt));

			Example mostDifficultExample = conn.getTheMostDifficult();
			if (mostDifficultExample != null) {
				mostDifficultLabel.setText(mostDifficultExample.getQuestion(direction) + " = " + mostDifficultExample.getAnswer(direction));
			} else {
				mostDifficultLabel.setText("");
			}
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(GUI.getInstance().getComponent(), e.getMessage(), "Database error", JOptionPane.OK_OPTION);
		}


		this.pack();
		this.okButton.setSelected(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel2 = new javax.swing.JPanel();
                jLabel13 = new javax.swing.JLabel();
                mostDifficultLabel = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                numberOfWordsLabel = new javax.swing.JLabel();
                okButton = new javax.swing.JButton();
                reset = new javax.swing.JButton();
                graph1 = new ucitel.forms.Graph();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setName("Form"); // NOI18N
                addWindowStateListener(new java.awt.event.WindowStateListener() {
                        public void windowStateChanged(java.awt.event.WindowEvent evt) {
                                formWindowStateChanged(evt);
                        }
                });
                addPropertyChangeListener(new java.beans.PropertyChangeListener() {
                        public void propertyChange(java.beans.PropertyChangeEvent evt) {
                                formPropertyChange(evt);
                        }
                });

                jPanel2.setName("jPanel2"); // NOI18N

                org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ucitel.Ucitel.class).getContext().getResourceMap(StatsForm.class);
                jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
                jLabel13.setName("jLabel13"); // NOI18N

                mostDifficultLabel.setText(resourceMap.getString("mostDifficultLabel.text")); // NOI18N
                mostDifficultLabel.setName("mostDifficultLabel"); // NOI18N

                jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
                jLabel1.setName("jLabel1"); // NOI18N

                numberOfWordsLabel.setText(resourceMap.getString("numberOfWordsLabel.text")); // NOI18N
                numberOfWordsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                numberOfWordsLabel.setName("numberOfWordsLabel"); // NOI18N

                okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
                okButton.setName("okButton"); // NOI18N
                okButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                okButtonActionPerformed(evt);
                        }
                });

                javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ucitel.Ucitel.class).getContext().getActionMap(StatsForm.class, this);
                reset.setAction(actionMap.get("reset")); // NOI18N
                reset.setText(resourceMap.getString("reset.text")); // NOI18N
                reset.setName("reset"); // NOI18N
                reset.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                resetActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(mostDifficultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                                        .addComponent(numberOfWordsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(numberOfWordsLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(mostDifficultLabel)
                                        .addComponent(okButton)
                                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                graph1.setName("graph1"); // NOI18N

                javax.swing.GroupLayout graph1Layout = new javax.swing.GroupLayout(graph1);
                graph1.setLayout(graph1Layout);
                graph1Layout.setHorizontalGroup(
                        graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 633, Short.MAX_VALUE)
                );
                graph1Layout.setVerticalGroup(
                        graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 205, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(graph1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(graph1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
	this.dispose();
}//GEN-LAST:event_okButtonActionPerformed

private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
	//this.pack();
}//GEN-LAST:event_formWindowStateChanged

private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
//this.pack();
}//GEN-LAST:event_formPropertyChange

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
	    conn.resetStats();
	    redraw();
    }//GEN-LAST:event_resetActionPerformed
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private ucitel.forms.Graph graph1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JLabel mostDifficultLabel;
        private javax.swing.JLabel numberOfWordsLabel;
        private javax.swing.JButton okButton;
        private javax.swing.JButton reset;
        // End of variables declaration//GEN-END:variables
	ConnectionToDB conn;
}
