package ucitel.entity;
// Generated 29.6.2011 14:38:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * 3Slovicka generated by hbm2java
 */
public class Slovicka  implements java.io.Serializable {


     private Integer id;
     private String czech;
     private String lang;
     private Integer weight;
     private Date lastAsked;
     private Integer correctlyAnswered;
     private String language;
     private Integer userId;
     private int caFromCzech;
     private String hint;
     private Integer themeId;
     private Date lastAskedToCzech;
     private Short grammar;

    public Slovicka() {
    }

	
    public Slovicka(String czech, Date lastAsked, String language, int caFromCzech, Date lastAskedToCzech) {
        this.czech = czech;
        this.lastAsked = lastAsked;
        this.language = language;
        this.caFromCzech = caFromCzech;
        this.lastAskedToCzech = lastAskedToCzech;
    }
    public Slovicka(String czech, String lang, Integer weight, Date lastAsked, Integer correctlyAnswered, String language, Integer userId, int caFromCzech, String hint, Integer themeId, Date lastAskedToCzech, Short grammar) {
       this.czech = czech;
       this.lang = lang;
       this.weight = weight;
       this.lastAsked = lastAsked;
       this.correctlyAnswered = correctlyAnswered;
       this.language = language;
       this.userId = userId;
       this.caFromCzech = caFromCzech;
       this.hint = hint;
       this.themeId = themeId;
       this.lastAskedToCzech = lastAskedToCzech;
       this.grammar = grammar;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCzech() {
        return this.czech;
    }
    
    public void setCzech(String czech) {
        this.czech = czech;
    }
    public String getLang() {
        return this.lang;
    }
    
    public void setLang(String lang) {
        this.lang = lang;
    }
    public Integer getWeight() {
        return this.weight;
    }
    
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
    public Date getLastAsked() {
        return this.lastAsked;
    }
    
    public void setLastAsked(Date lastAsked) {
        this.lastAsked = lastAsked;
    }
    public Integer getCorrectlyAnswered() {
        return this.correctlyAnswered;
    }
    
    public void setCorrectlyAnswered(Integer correctlyAnswered) {
        this.correctlyAnswered = correctlyAnswered;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public int getCaFromCzech() {
        return this.caFromCzech;
    }
    
    public void setCaFromCzech(int caFromCzech) {
        this.caFromCzech = caFromCzech;
    }
    public String getHint() {
        return this.hint;
    }
    
    public void setHint(String hint) {
        this.hint = hint;
    }
    public Integer getThemeId() {
        return this.themeId;
    }
    
    public void setThemeId(Integer themeId) {
        this.themeId = themeId;
    }
    public Date getLastAskedToCzech() {
        return this.lastAskedToCzech;
    }
    
    public void setLastAskedToCzech(Date lastAskedToCzech) {
        this.lastAskedToCzech = lastAskedToCzech;
    }
    public Short getGrammar() {
        return this.grammar;
    }
    
    public void setGrammar(Short grammar) {
        this.grammar = grammar;
    }




}


