package ucitel.entity;
// Generated 29.6.2011 14:38:58 by Hibernate Tools 3.2.1.GA



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private UsersId id;
     private String password;

    public Users() {
    }

    public Users(UsersId id, String password) {
       this.id = id;
       this.password = password;
    }
   
    public UsersId getId() {
        return this.id;
    }
    
    public void setId(UsersId id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


